### ISSUE TITLE
Collections can only be valid after they have been read from a file

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#104]
`Collection::isValid` only returns `true` if the collection has previously been read from a file as the `m_isValid` member is defaulted to `false` and only set to `true` in `Collection::prepareAfterRead`. Naively I would have expected that a newly created collection should also be valid, e.g.

```cpp
podio::EventStore store;
auto& collection = store.create<ExampleCollection>("aCollection");
collection.isValid(); // should be true but currently returns false
```

In my opinion the validity of a collection should not depend on whether it has been read from file or whether it has previously been created without an intermediate I/O operation. For the user this should be completely transparent and it should be possible to not care from where the collection is provided as long as it is known to the `EventStore`.

**Comment by hegner** [comment]
Thanks for spotting. This is a mistake in the interface. This validity check should have been kept internal to the implementation.

**Comment by hegner** [comment]
PR #191 fixes this issue
