### ISSUE TITLE
Is there an example for multi-thread or parallel Input/Output

### ISSUE THREAD

**Issue by whyellowmiao** [AIDASoft/podio#108]
I do not meet any problems and I just want to ask a question.
It is said that podio would have good performance in multi-thread or parallel computing. Is there an example for multi-thread or parallel Input/Output now in the newest version of podio?

**Comment by tmadlener** [comment]
Using the `Frame` and the accompanying readers this should be achievable now. Feel free to re-open if that is not the case.
