### ISSUE TITLE
General discussion: Using podio outside of HEP

### ISSUE THREAD

**Issue by joequant** [AIDASoft/podio#110]
Hi,

Just starting a general discussion topic about using podio outside of HEP.  Right now I'm working with a logistics company here in Hong Kong looking at using HEP software for things like algorithmic trading and financial data processing.  The idea is to see if it would be possible to take software and frameworks like GAUDI and feed in stock trades rather than the detector events.

One of the problems in fintech is that there is a "tragedy of the commons" issue every bank and hedge fund uses their own event processing system.   Once you've spent $$$$$ setting up a trading system, you don't want to share code.  Code in the HEP community tends to be shared, because you need other groups to reproduce your results, and the "secret sauce" is the data and not the data reduction.

This is all very preliminary, and I don't know if it will turn out that the code is in fact the same, but that's research.  However, haven't a high performance collection object that can handle low latency and multi-threading seems to be something that's a common component.

**Comment by joequant** [comment]
Just a note as to why podio looks very interesting is that it looks a lot like something that exists in most investment banks.  So you have a bank with hundreds of thousands of different instruments.  Stocks, bonds, and weird stuff.  The Federal Reserve then asks the bank "so convince us that in a crisis, you won't go poof."  So there have this system by which you put all of the different instruments into this monster data structure, then run this through a monte carlo engine, and then come up with statistics.

Sounds familiar?

The trouble is that every bank has the same version of the code and there's no interoperability.  And because there is no standardization, the government can't run system wide calculations.

https://www.sec.gov/rules/proposed/2010/33-9117.pdf

**Comment by hegner** [comment]
Thanks. Sounds indeed quite interesting! Maybe you can tell more during another meeting?

**Comment by tmadlener** [comment]
Closing this for now. If it becomes relevant again, feel free to open again.
