### ISSUE TITLE
Discussion about python code generator update / refactoring

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#116]
I have started to work on making the python code that fills the templates to generate the full classes a bit more readable. Ideally this would also result in better maintainability. While doing this I have stumbled upon some things for which I didn't really find anything in the documentation (or equally likely, I have missed it).

- Some fields in the data model syntax are not really used, respectively after reading them in, they are not used for the class generation. E.g.:
  - `const_declaration` in the `ExtraCode` field of components (#115)
  - `ConstExtraCode`, `TransientMembers`, `Typedefs` for the datatypes

- On the other hand it seems that `const_declaration` and `const_definition` should have been placed under the `ConstExtraCode` but are now generally placed in `ExtraCode`. It is not entirely clear from the documentation what the difference between `declaration` and `const_declaration` is or should be. As far as I have gathered the former goes only into the `DataType`, while the latter additionally also goes into the `ConstDataType`(?)

I am not sure what the original design idea was, but it seems to me that it is no longer rigorously followed.

----

I have also been playing with a python [schema validation library](https://pypi.org/project/schema/), and from a few [quick tests](https://gist.github.com/tmadlener/6f97cc77aabbe7a6b821b6bd74344c27#file-podio_schema_proto-py-L155-L176) it looks to be feasible to apply to the podio datamodel files. In the gist I already do some very basic parsing of the members of the datatypes. I think to get the very basic errors that can happen in the yaml file this would be enough. It might even be possible to do a more thorough validation, but that would need to be tested. The main question here is, is it OK to pull in another dependency for this or should we aim to do this without?

**Comment by joequant** [comment]
One idea that I'd like to throw out is whether it would be a good idea to include templated classes so instead of merely having

class ExampleHitObj y{
}

you also have

template<>
class Obj<ExampleHit> {
}

typedef ExampleHitObj Obj<ExampleHit>

My suspicion is that if the classes were templatized that some of the code duplication could be removed
and you could write generic functions for specificing the reltationship between Obj and Data, and you 
can do things like write generic functions to move between const and non-const objects and convert to and
from STL and other frameworks.

Thoughts?

**Comment by tmadlener** [comment]
That could potentially make the code generation a bit easier to do. Also the `Obj` classes are not really user facing, since they just handle the relations under the hood, but the interaction with them is all done through the actual class. So I think in principle nothing speaks against trying to have a template solution. However, again the relations between the different objects might be a problem, because they can differ greatly between different objects and that requires different members to be present in the class. I don't think that is possible with a template class, but maybe with newer c++ standards it is?

Have you tried to implement the `Obj` as a template class that can be reused by simply instantiating it differently?

**Comment by joequant** [comment]
Still trying to get used to the code (and still spending a crazy amount of
time filling out bureaucratic forms), but I can
do a quick experiment to try to templatize things to see if anything breaks.

**Comment by tmadlener** [comment]
Since #117 and #120 have been merged I will close this as the main questions have been addressed there.
