### ISSUE TITLE
Thread for newbie questions / FAQ

### ISSUE THREAD

**Issue by joequant** [AIDASoft/podio#118]
Some newbie questions:

1) What environment variables need to be set in order to get root loading to work?

2) Is there is simple text file read / write?  I'd like to have a test system that just does a simple ascii/load save.

3) Any interest is setting up a chat room to deal with newbie questions?  :-) :-)  If so what's the preferred forum?

Looking through the code, the collections itself seems pretty simple, but the messy bits are the read/write with root.

**Comment by andresailer** [comment]
### 1
If you mean the loading of the dictionary on demand, then the LD_LIBRARY_PATH has to contain the path where the *.rootmap files are found

### 2
There is no ascii reader/writer for podio data at the moment.

### 3
I don't really have an opinion on this. I like things being on github for their publicity.

**Comment by joequant** [comment]
There's a file src/ASCIIWriter.cc and a unit test for ascii writing.  Is
that a data writer or something else.

**Comment by andresailer** [comment]
You're totally correct.
There is also an example for that https://github.com/AIDASoft/podio/blob/6019f0f3eb9c4924f8fd21d48cbbd30aab8784cc/tests/write_ascii.cpp

**Comment by tmadlener** [comment]
To be addressed with #379
