### ISSUE TITLE
ROOTReader doesn't handle meta data properly when reading from multiple files

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#132]
When reading from more than one file the reading of the meta data breaks after the first file has been read. The `read-multiple` test doesn't actually cover this so it has gone undetected until now.

The reason seems to be that in
https://github.com/AIDASoft/podio/blob/6a1e506efbd4d998beb05b07de8d38898fde4308/src/ROOTReader.cc#L18-L20

the call to `m_chain->GetFile()` possibly still returns the "old" file and has not necessarily switched to the "new" file yet. For this to happen a call to `m_chain->LoadTree(m_eventNumber)` needs to happen, which is happening only in `readCollection`:
https://github.com/AIDASoft/podio/blob/6a1e506efbd4d998beb05b07de8d38898fde4308/src/ROOTReader.cc#L84

This issue is easily solved for meta data that is expected to change with every event / run. However, it is a bit harder, also from a conceptual point of view, for meta data that are read at the beginning of the file which is done in `openFiles`, but only for the first file. It is possible that the stored meta data in the next file are different, but currently this is not taken into account when switching files.

**Comment by hegner** [comment]
There are two problems:

1. the (memory) bookkeeping of this data is left to the magics of ROOT. 
2. It seems there is no record of the validity of metadata, but only implicit assumptions
