### ISSUE TITLE
Discussion: Interplay between Readers, Writers, EventStore and Collections

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#140]
I would like to start a discussion about how to improve the interplay between the different entities that are involved in reading and writing the data as well as the ones that provide access to the contents of the events. I have broadly structured this into three topics, but they are all somewhat related, which is also why I have kept them in one issue here.

# Ownership of resources
From the implementation of the `EventStore` it seems like it takes ownership of the resources that are provided by, e.g. the `ROOTReader`. I am not sure if this comment https://github.com/AIDASoft/podio/blob/d4a02651332e2fe3ffbac4e99fa61b34600a16fa/src/ROOTReader.cc#L163-L167
is outdated or still relevant, but I would like to take it as a starting point for a discussion regarding where to best put the ownership of different resources. If nothing else, there will at least be some sort of documentation at the end that clearly states who takes responsibility for which resources. It also looks like that somewhere in the process memory is leaked, see #139.

At the moment there are only two types of data:

#### Collections (data buffers)
I think in this case it makes sense that the `EventStore` owns the data, respectively takes responsibility for calling the necessary `clear` methods of the collections. In this case the collections need to make sure that they truly free all resources when asked to do so.

#### Metadata
There are two things that are currently referred to as metadata. The metadata that is necessary to reconstruct the collections and the relations between them, and the "user level" metadata at the Event, Run or Collection level. The former is only the `CollectionIDTable` that is necessary to correctly assign the IDs to the names of the collections, while the latter are currently stored as `GenericParameters`.

I think for both the collection data and the metadata it makes sense that the EventStore owns the data and is responsible for properly cleaning them up if they are no longer used. Also in view of a possible multi threading capable version of the EventStore it makes sense that the EventStore receives all the necessary data from the reader and then handles them from there and doesn't need to query the reader ever again. This is not the case at the moment, where it is possible that some collections are lazily loaded throughout the event.

I am not entirely sure whether the writers could serve as a sort of sink, or if it is easier to simply pass a reference of the data to the writer and still let the EventStore clean up the data once they are written.

# Synchronization
When reading from more than one file, or at a run change it might become necessary for the reader to signal such a change to the EventStore, respectively at least trigger the update of some of the metadata. #132 covers a bug in the reader, where even upon request from the EventStore potentially the wrong data are provided.

I think ideally the EventStore is completely agnostic to such changes and is simply able to provide the correct data to the user. However, I am not entirely sure whether this is actually possible in all cases. E.g. the `CollectionIDTable` might change at a file change (for whatever reason).

# Const correctness
As mentioned in #136 the current implementation of providing access to the Event-, Run- and CollectionMetaData is not const-correct. There were also some discussions already in #109 and in [this comment](https://github.com/AIDASoft/podio/pull/95#issuecomment-644635902) that the current implementation of const-handling is not completely consistent overall.

Const-correctness (almost) mandates that once a collection has been passed to the EventStore after creation it should be non-mutable for the rest of it's lifetime. Maybe the interface should reflect this, in a way that the current `registerCollection` becomes the canonical way of adding collections to the EventStore?

**Comment by hegner** [comment]
Let me comment on the various points.

1. Ownership: it very much depends on the vision for how PODIO will support multiple I/O backends. Either the EventStore is merely a thin facade on top of the reader / writer which have all the business logic. Or - what makes more sense - the EventStore does most of the book keeping and thus the I/O backends mainly bridge to the memory models of the I/O libs. At least in first order. This allows as well to mix different backends and format conversion. @tmadlener made a good point about the writer acting as a sink. I think that makes a lot if sense. We should however make the interfaces more clear about ownership transfer.

The metadata handling to me needs a rethinking entirely. 

2. Synchronization: for this I will need to explain possible models in a meeting if OK with everybody

3. const correctness: goes along with it

**Comment by hegner** [comment]
The point about the sink is that the write can happen asynchronously as defined by the logics of the writer rather than tied to the lifetime of an event.

**Comment by andresailer** [comment]
See also discussion  https://indico.cern.ch/event/983031/#4-discussion

**Comment by tmadlener** [comment]
No longer relevant with deprecation of the EventStore and the Frame based model.
