### ISSUE TITLE
CollectionIterator does not fully satisfy iterator concept

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#150]
It currently seems to be impossible to use podio collections with the STL algorithms operating on iterator ranges, because the `CollectionIterator` does not provide enough information, leading the compiler complaining about (greatly abbreviated to the crucial line):

```
/usr/include/c++/9/bits/stl_iterator_base_types.h:205:5: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<edm4hep::MCRecoParticleAssociationCollectionIterator>’
```

I think having a correctly implemented const-iterator is something we should aim for, to at least enable the usage of STL algorithms that can be used on ranges of const-iterators.

**Comment by whit2333** [comment]
IMO, this is critical. I have almost given up and started using the raw `*Data` classes which are not accessible otherwise.
