### ISSUE TITLE
Discussion: ObjectID's and invalids

### ISSUE THREAD

**Issue by joequant** [AIDASoft/podio#160]
This came up as I was fixing up signed compiler warnings.  

Right  now ObjectID is set to signed int, which seems odd since it should be unsigned.  However, ObjectInvalid is set to -2

I think this could be made to work if ObjectID invalid is set to static_cast<unsigned>(-2) which makes it a very high integer.

The reason this has been to looked at is that since ObjectID is a long, I can easily imagine a situation where you have more than 2 billion objects at which point things will suddenly go weird.

**Comment by tmadlener** [comment]
See also #170 for a more detailed discussion.

**Comment by hegner** [comment]
@joequant - is this item still a concern for you considering #170 ? If not, I will close this item
