### ISSUE TITLE
cmake finds "unsuitable" python version 

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#161]
Just pulled the latest master and I am running into the following Problem on Ubuntu 20.04 with cmake 3.16.3

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Python: Found unsuitable version "3.8", but required is
  exact version "3.8.5" (found /usr/lib/x86_64-linux-gnu/libpython3.8.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
  /usr/share/cmake-3.16/Modules/FindPython.cmake:304 (include)
  CMakeLists.txt:86 (FIND_PACKAGE)
```

I haven't tried yet with other versions of cmake, but it seems that the changes introduced in #153 are also having problems on when used with cmake 3.16.3 (at least on Ubuntu 20.04)

**Comment by petricm** [comment]
In certain versions of CMake the Find Python does not resolve the patch number, therefore there is a exclusion of certain versions

https://github.com/AIDASoft/podio/blob/cf3d239cbc4932e2b1d7ee42bcbef55ee869b3c1/CMakeLists.txt#L79-L80

apparently we did not catch all

**Comment by tmadlener** [comment]
Alright, so I will just add 3.16.3 as well there. Thanks for the quick reply.

**Comment by petricm** [comment]
As we test on LCG releases 
LCG_97 -> cmake 3.14.3
LCG_98 -> cmake 3.17.3

so we know it works for these versions, and we found the exception (referenced in the snippet), but we did not go though every patch between those two versions.

**Comment by tmadlener** [comment]
Could this also be related being run on Ubuntu? Maybe the fact that `libpython` does not have the full major.minor.patch version in its name could lead to problems as well?

**Comment by petricm** [comment]
Interesting point, could you try with 3.17.3, there we consider it works, but I don't know if we tested with ubuntu system python

**Comment by tmadlener** [comment]
That seems to work, at least with a spack installed version of cmake. However, I seriously hope that that doesn't make a difference.
