### ISSUE TITLE
Too many levels of symbolic links in CI

### ISSUE THREAD

**Issue by petricm** [AIDASoft/podio#163]
https://github.com/AIDASoft/podio/blob/cf3d239cbc4932e2b1d7ee42bcbef55ee869b3c1/.github/workflows/test.yml#L32

Each cvmfs repo needs to be mounted individually, and not `-v /cvmfs:/cvmfs` otherwise you might end up in `Too many levels of symbolic links`

**Comment by vvolkl** [comment]
This should be fine if it's /cvmfs:/cvmfs:shared, I think

Also we should use the cvmfs GitHub Action from cvmfs-contrib

**Comment by petricm** [comment]
But it's not, check the CI of the last commit to master
