### ISSUE TITLE
Switch to Catch2 v3 in unittests

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#164]
The (upcoming) Catch2 v3 can be built as a static library that can be linked against. This would allow to build it only once for the whole stack instead of building it for each project separately from the header-only v2.

Two PRs are already going in that direction:
https://github.com/key4hep/k4SimDelphes/pull/17
https://github.com/key4hep/EDM4hep-utils/pull/1

This is not really urgent, but could be a nice "first issue".

**Comment by hegner** [comment]
solved with #206
