### ISSUE TITLE
Performance degradation for root 6.22/06 compared to 6.20/04

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#179]
There seems to be a quite serious performance degradation between root 6.20/04 and 6.22/06.

Running one of our benchmark cases using different versions of root yields the following report: https://github.com/tmadlener/podio_benchmarking/tree/c5aebc017b99f572a84082f505958dafbd78b79b/results/k4SimDelphes/compare_root_versions

It can clearly be seen that in total time root 6.22/06 is about a factor 2 slower when reading and writing compared to root 6.20/04. This seems to be entirely driven by much longer per event times (for the easiest comparison look at the plots).

Will have to investigate if this is due to some changed defaults in roots I/O or if this is due to some other reason.

**Comment by clementhelsens** [comment]
your plot looks like there is an overall 250micro second shift in all events.
Could it be some latency has been introduced ?

**Comment by tmadlener** [comment]
Good question.  I have opened a thread in the root forum: https://root-forum.cern.ch/t/serious-degradation-of-i-o-performance-from-6-20-04-to-6-22-06/43584
Maybe the root devs can point us to the source of this problem.
