### ISSUE TITLE
Document `Const`* Interfaces

### ISSUE THREAD

**Issue by vvolkl** [AIDASoft/podio#198]
The docs make no mention of the `Const`* classes users now need to use for reading. Here: https://github.com/AIDASoft/podio/blob/master/doc/design.md#layout-of-objects the user visible type still is mentioned as `Hit`

**Comment by tmadlener** [comment]
With #205 the `Const` classes are gone and the mutability in the user layer is now hopefully better documented in https://github.com/AIDASoft/podio/blob/master/doc/design.md#the-user-layer
