### ISSUE TITLE
Object assignment operator causes duplicated releasing

### ISSUE THREAD

**Issue by feipengsy** [AIDASoft/podio#200]
It seems the generated object assignment operator doesn't increase the reference count of the underlying Obj.

For example, this is the generated assignment operator:

```C++
Hit& Hit::operator=(const Hit& other) {
  if ( m_obj != nullptr) m_obj->release();
  m_obj = other.m_obj;
  return *this;
}
```

And some code like this would cause problems:

```C++
std::map<int,Hit> HitMap;
for(...) {
    Hit aHit = Hit();
    ...
    HitMap[i] = aHit;
}// Hits in the HitMap becomes invalid after the loop.
```

Is this by design or unexpected? Maybe add a m_obj->acquire() as well.

**Comment by tmadlener** [comment]
Hi @feipengsy,

thanks for reporting this. This is indeed a bug and the assignment operator should `acquire` to increase the reference count.
