### ISSUE TITLE
Cleanup / reorganize tests

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#233]
The current read / write tests are becoming a bit large and having them a bit more modular would make it easier to extend them towards also serving as regression tests (e.g. to catch things like #229 earlier). In sight of schema evolution that is something that we probably need in any case.

**Comment by hegner** [comment]
I think the last work on PR #412 and all the additions for the frame testing already show that things are not as monolithic any more.  We as well deprecated a few old tests. Thus I close this ticket
