### ISSUE TITLE
LCIO backward (read) Compatibility 

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/podio#27]
Hello,

It would great if PODIO could be made to read LCIO files. What are the major challenges to implementing this? 

Is it as straightforward as creating an SIOReader and use the right LCIO data model?

Cheers,
Whit

**Comment by hegner** [comment]
There is a project by Frank Gaede working on exactly that: https://stash.desy.de/projects/IL/repos/plcio/browse

**Comment by whit2333** [comment]
Thanks.  This is good to hear. Do you know what is the current status is?

**Comment by hegner** [comment]
Currently a little bit dormant, though I had a chat with Frank Gaede for how to re-start it. Maybe you could ping him as well.
