### ISSUE TITLE
macOS CI workflows are failing in the CVMFS mount

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#275]
It looks like there are some problems in the macOS CI workflows. They run into a segmentation fault while mounting cvmfs repositories:
See, e.g. this run: https://github.com/AIDASoft/podio/runs/5734210695?check_suite_focus=true#step:3:155

**Comment by andresailer** [comment]
I opened a ticket with cvmfs, maybe they have some insight. https://github.com/cvmfs/cvmfs/issues/2882

**Comment by tmadlener** [comment]
Fixed by update of macOS. See cvmfs issue (above) for more information.
