### ISSUE TITLE
Can podio support fixed-width integers?

### ISSUE THREAD

**Issue by drbenmorgan** [AIDASoft/podio#28]
I'm starting to try out podio for use in the SuperNEMO experiment. One immediate issue I encountered is that our current data model uses fixed width integers from the Standard Library `cstdint` such as `uint16_t`.  Podio's class generator complains about the use of these (naturally!), but are there reasons podio could not support them?

I'd be happy to experiment with adding them and submit a PR if there's no blocker - it looks like `ClassDefinitionValidator` would be the place to do this, but clearly an extra `#include <cstdint>`s would be needed somewhere (like for `std:string`?)

**Comment by hegner** [comment]
I understand the use case. I think the best approach would be if we extend the definition of the "Members" (as output of the parsing/reading step) to contain a field denoting a header to include. The validator could then get a map of those. Replacing the special treatment of strings as implemented now. A PR along those lines would be great.

**Comment by drbenmorgan** [comment]
Thanks! I'll wait on the update to strings and then use that as an example - will continue to use plain ints for now.

**Comment by tmadlener** [comment]
Fixed by #186
