### ISSUE TITLE
Replace `obj_needs_destructor` by more general concept

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#288]
Currently we only generate a destructor for the `Obj` objects if it is necessary, e.g. here:

https://github.com/AIDASoft/podio/blob/469b739c855841ed7821d2a43e3f8c779a471e02/python/templates/Obj.h.jinja2#L35-L39

which is populated in the generator, here:

https://github.com/AIDASoft/podio/blob/469b739c855841ed7821d2a43e3f8c779a471e02/python/podio_class_generator.py#L259-L260

The condition in the generator describes a rather general class of datatypes, i.e. ones that have no relations or vector members. I think the name of `obj_needs_destructor` should be changed to something that better reflects this more general condition. E.g. `is_trivial_type` (or something similar).

**Comment by soumilbaldota** [comment]
We can fix it by changing the variable names to trivial_types instead of needs_destructor 

     trivial_types = datatype['VectorMembers'] or datatype['OneToManyRelations'] or datatype['OneToOneRelations']
     datatype['is_trivial_type'] = trivial_types

And is_trivial_type instead of obj_needs_destructor


      {% if is_trivial_type %}
        virtual ~{{ obj_type }}();
      {% else %}
        virtual ~{{ obj_type }}() = default;
      {% endif %}

Could you assign this issue to me ?

**Comment by soumilbaldota** [comment]
I have opened a pull request with the above changes.
