### ISSUE TITLE
static version of getValueTypeName() and friends

### ISSUE THREAD

**Issue by faustus123** [AIDASoft/podio#313]
It would be convenient in certain cases to have the following members of the type-specific collection classes be static:

getTypeName()
getValueTypeName()
getDataTypeName()

context:
In an application I'm writing I have a templated function that gets passed in a collection class as one of the template parameters. It is creating a collection of that type and partially deriving the name of the collection from what is returned from getValueTypeName(). A natural way to write this for a template parameter C where e.g. C=ClusterCollection would be:

auto name = C::getValueTypeName() + suffix;

As it currently is, I have to do this:

C tmp;
auto name = tmp.getValueTypeName() + suffix;

If you really want those methods to be overridden by subclasses, then maybe you could consider adding static versions to supplement the class for these types of scenarios.

**Comment by hegner** [comment]
Hi @faustus123 - I think it makes perfect sense to make the information statically available.
