### ISSUE TITLE
PODIO license

### ISSUE THREAD

**Issue by hegner** [AIDASoft/podio#324]
As discussed a few times in the past, we should finally move the PODIO license from GPL to Apache 2. For this I would ask all contributors to PODIO so far to sign off in this ticket and give their OK. 

This is relevant for 

- [x] @tmadlener
- [x] @jlingema
- [x]  @gaede
- [x]  @cbernet
- [x]  @vvolkl 
- [x] @andresailer
- [x]  @JavierCVilla
- [x]  @peremato 
- [x] @drbenmorgan
- [x]  @zaborowska
- [x]  @joequant
- [x]  @soumilbaldota
- [x]  @fdplacido
- [x]  @wdconinc
- [x]  @graeme-a-stewart 
- [x] @kjvbrt 

Fixes #208

**Comment by graeme-a-stewart** [comment]
Good for me!

* [x] @graeme-a-stewart

**Comment by jlingema** [comment]
Good for me!

**Comment by tmadlener** [comment]
:+1: good for me.

**Comment by JavierCVilla** [comment]
Good for me

**Comment by cbernet** [comment]
Hi all ! fine with me

**Comment by gaede** [comment]
Fine with me.

**Comment by andresailer** [comment]
Ok for me!

**Comment by fdplacido** [comment]
Good for me.

**Comment by soumilbaldota** [comment]
Good for me.

**Comment by vvolkl** [comment]
OK for me too.

**Comment by zaborowska** [comment]
sorry for the delay, ok for me too!

**Comment by joequant** [comment]
ok for me

**Comment by drbenmorgan** [comment]
Fine for me (and sincere apologies for the delay!)!

**Comment by hegner** [comment]
Great. Thanks to all!

**Comment by vvolkl** [comment]
I think we need Juraj @kjvbrt  as well to sign off on this ( see https://github.com/AIDASoft/podio/commits?author=kjvbrt thanks @wdconinc for spotting this)

**Comment by kjvbrt** [comment]
I agree with the change of the licence.
