### ISSUE TITLE
Feature request: python writing test (or does writing in python not work?)

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#326]
I'm writing a simple filter for podio files, hoping to depend only on podio. I was hoping to write this entirely in python, but there's only a `read.py` which makes me wonder if writing in python is supported. Would it be possible to include a `read_and_write.py` example?

**Comment by tmadlener** [comment]
At least currently there is no real mechanism for writing in python. It might be possible to create a `ROOTWriter` explicitly via the python bindings, but I am not even entirely sure about that since we do not explicitly put it into the podio dictionary.

**Comment by wdconinc** [comment]
Ok, that's fine. I've just written it all in C++.

**Comment by wdconinc** [comment]
I'm fine with you closing this, unless you want to keep it open as a potential future development opportunity.
