### ISSUE TITLE
Data model extension should add upstream include directory to target

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#330]
It would be useful if the podio macros could accept the upstream data model include directory(ies) and attach them to the target that is created, for example at 
```cmake
PODIO_ADD_DATAMODEL_CORE_LIB(eicd "${headers}" "${sources}"
  OUTPUT_FOLDER ${CMAKE_CURRENT_BINARY_DIR}
  INCLUDE_DIRECTORIES ${EDM4HEP_INCLUDE_DIRECTORY}
)
```
This would then add a `target_include_directories` to the target. Right now this requires for users to dive into the macro definition to determine the target name, and assuming it won't change over time.

Using `include_directories` is too blunt of a tool in downstream code that may not want this included for all targets.

Without include, this fails.
```console
make: Entering directory '/home/wdconinc/EIC/eicd/build'
make[1]: Entering directory '/home/wdconinc/EIC/eicd/build'
make[2]: Entering directory '/home/wdconinc/EIC/eicd/build'
make[2]: Leaving directory '/home/wdconinc/EIC/eicd/build'
make[2]: Entering directory '/home/wdconinc/EIC/eicd/build'
[  1%] Building CXX object CMakeFiles/eicd.dir/src/ReconstructedParticle.cc.o
In file included from /home/wdconinc/EIC/eicd/build/eicd/ReconstructedParticleObj.h:7,
                 from /home/wdconinc/EIC/eicd/build/eicd/ReconstructedParticle.h:6,
                 from /home/wdconinc/EIC/eicd/build/src/ReconstructedParticle.cc:4:
/home/wdconinc/EIC/eicd/build/eicd/ReconstructedParticleData.h:7:10: fatal error: edm4hep/Vector3f.h: No such file or directory
    7 | #include "edm4hep/Vector3f.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/eicd.dir/build.make:76: CMakeFiles/eicd.dir/src/ReconstructedParticle.cc.o] Error 1
make[2]: Leaving directory '/home/wdconinc/EIC/eicd/build'
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/eicd.dir/all] Error 2
make[1]: Leaving directory '/home/wdconinc/EIC/eicd/build'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/wdconinc/EIC/eicd/build'
```

**Comment by tmadlener** [comment]
Hi @wdconinc, sorry this slipped through until now.

I am not sure what I am missing, but I suppose it is something. Why does simply linking against the upstream target not work, here? I.e.
```cmake
PODIO_ADD_DATAMODEL_CORE_LIB(eicd "${headers}" "${sources}"
  OUTPUT_FOLDER ${CMAKE_CURRENT_BINARY_DIR})
target_link_library(eicd PUBLIC EDM4HEP::edm4hep)
```
This should in principle propagate all the necessary dependencies. Is this not the case for you?

The target name for the upstream EDM is in principle not something that is defined in the macro, but rather by how the upstream EDM exports their targets.

**Comment by wdconinc** [comment]
Yes, this can be closed.

`target_link_library(eicd PUBLIC EDM4HEP::edm4hep)` does mean indeed that `target_include_directories` is not necessary.

It's just that NOT having the `target_link_library(eicd PUBLIC EDM4HEP::edm4hep)` line ALSO worked in our case (except on Mac), and in that case `target_include_directories` IS necessary. I'm not exactly sure why, but probably because of some overlap in `LD_LIBRARY_PATH` with other dependencies.

In any case, we are now using `target_link_library(eicd PUBLIC EDM4HEP::edm4hep)` explicitly, per the [instructions](https://github.com/AIDASoft/podio/blob/v00-15/doc/datamodel_syntax.md?plain=1#L157).
