### ISSUE TITLE
Should `OneToManyRelations` also work for mutable types?

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#347]
The current implementation of the `RelationRange` ([source](https://github.com/AIDASoft/podio/blob/master/include/podio/RelationRange.h)) that is used to give ergonomic access to `OneToManyRelations` currently only gives access to immutable types, e.g.
```cpp
auto mcParticles = edm4hep::MCParticleCollection();
auto mc = mcParticles.create();
// ... add some daughters/parents
for (auto p : mc.getParents()) {
  // p.setPDG(11);  // this fails, because p is an edm4hep::MCParticle here
}
```
It is possible to work around this via
```cpp
// as above
for (auto p : mc.getParents()) {
  auto parent = mcParticles[p.getObjectID().index];
  parent.setPDG(11);  // this works, because now we get a edm4hep::MutableMCParticle again
}
```

I think it should be possible to have an implementation of the `OneToManyRelation` access functionality that behaves as expected in this case. Potentially one has to introduce a corresponding `MutableRelationRange`. I am not yet entirely sure whether I have thought of all possible edge cases here, so keeping this issue to keep track of them in case they are discovered.

**Comment by tmadlener** [comment]
It is in fact not possible at all to get a mutable `OneToManyRelation` object from a `Mutable` object, because also the `getRelation(unsigned)` methods are generated to return the immutable objects. Also the `relation_begin` and `relations_end` methods are `std::vector<RelationType>::const_iterators`.

It is not entirely clear to me yet whether we actually want to have mutable access to `OneToManyRelations` (or `OneToOneRelations`, because wether that is a valid access or not potentially depends on whether the collection in which they live is still mutable or already immutable. On the other hand there are certain cases where such an access would be very handy, and there might not always be a workaround for solving them differently.

**Comment by tmadlener** [comment]
After more consideration, this is not something that we want as we do not want to have a "backdoor" to change related objects (which might live in another collection). The example above is a rather special case where we can assume that all objects that we want to change live in the collection that we are currently still filling / modifying.

**Comment by hegner** [comment]
Thanks! I think that is the best approach
