### ISSUE TITLE
Required match of Python versions?

### ISSUE THREAD

**Issue by jmcarcell** [AIDASoft/podio#366]
https://github.com/AIDASoft/podio/blob/52064ba2217f45c27eb992f2b295d4be1508fa52/CMakeLists.txt#L93
This line requires the Python version used when compiling ROOT and when building podio to be the same but this is not always needed. For example, in my linux distribution I get ROOT compiled with Python 3.10.8 but I get Python 3.10.9 in the system so running `cmake` fails, although if I relax the rule it compiles and runs fine. What about relaxing the rule so that the patch number (major.minor.patch) is not required to match exactly and a warning is displayed in the case that they don't match? I volunteer for a PR

**Comment by vvolkl** [comment]
The ROOT developers claim that  using even a different patch version than was used to build ROOT can lead to potential issues in pyroot, but I agree, in practice this is often overly strict. See https://github.com/AIDASoft/DD4hep/pull/997 , I'd suggest to replay the same for podio.
