### ISSUE TITLE
CollectionIDs should not depend on the insertion order

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#381]
Currently the order of insertion into a `Frame` determines the `collectionID`. This is extremely unstable, especially in multi threaded contexts, but also in cases where collections might be missing. The `collectionID` should be something stable, even across different processes and should ideally only depend on the collection name. In principle hashing the name should be good enough for this, however with only 32 bits available at the moment collisions are not unlikely, and even with 64 bits there should probably still be a way to handle collisions.

**Comment by nathanwbrei** [comment]
Can we expedite this? EICrecon has just switched to using podio Frames, and JANA does not enforce a universal ordering in which factories get called/collections get added. To avoid this bug, we have to follow a convention of how we request data in every single factory. Sooner or later, someone is going to violate this convention and the writer will segfault. Also, my attempts at a temporary workaround have been stymied by the fact that setID() doesn't do anything:

```c++
TEST_CASE("PodioCollectionIDBehavior") {
    podio::Frame frame;
    ExampleHitCollection c;
    c.setID(222);
    REQUIRE(c.getID() == 222);  // Passes

    const auto& cc = frame.put(std::move(c), "c");
    REQUIRE(cc.getID() == 222); // Fails

    const auto& ccc = frame.get<ExampleHitCollection>("c");
    REQUIRE(ccc.getID() == 222); // Fails
}
```

**Comment by tmadlener** [comment]
The ID gets reset internally, here in line 421 here:
https://github.com/AIDASoft/podio/blob/f4c9219ddde59b1efc73db3fd9c25139222a7b3c/include/podio/Frame.h#L410-L424

We have plans to make the CollectionIDTable use hashes of the names instead of insertion order, but we are not yet sure how to best deal with collisions yet. If you have any clever idea for that let us know.

**Comment by nathanwbrei** [comment]
Hi Thomas, thanks for the prompt reply! I don't have a clever idea for hashing collection names at the moment, though if something pops into my head I will let you know.

I agree that making collection IDs an implementation detail not exposed to the user would be ideal. However I also believe that the list of collection names (and possibly their corresponding types) is something that has to be kept consistent  between Frames (and validated!). Thus this list shouldn't be the responsibility of any individual Frame. 

I think all we really need to do is allow the user to provide their own CollectionIDTable for each frame as an optional ctor arg. This table would extend and validate the table already provided by ROOTFrameReader, etc. I haven't tried this in practice yet, but the consequences I predict are:

- We might not know this list initially, but we will after processing the first event
- We can keep using the monotonically increasing collectionIDs
- This would allow us to detect and throw a clean exception if the user adds a collection to a later event which was not present in the first event, and tries to use ROOTFrameWriter.
- This would fix the problem of frames from multiple input files being written to one (or multiple) output files, which is another one of JANA's architectural choices that doesn't necessarily play nicely with PODIO's current assumptions
