### ISSUE TITLE
ROOTFrameReader crash when reading multiple edm4hep files

### ISSUE THREAD

**Issue by lkosarz** [AIDASoft/podio#411]
Podio crashes when reading multiple edm4hep.root files. However, it works fine for a single file.
ROOTFrameReader produces memory leaks when opening multiple files with a separate ROOTFrameReader instance per file - may be related.

 - OS version: Debian Linux 3.10.0-1160.71.1.el7.x86_64
 - Compiler version: gcc (Debian 12.2.0-14) 12.2.0
 - PODIO version: tag or commit ID, or GitHub branch
 - Reproduced by: ROOT 6.26/10, Geant4 11.1.1, cmake version 3.24.3, singularity, eic-shell, dd4hep-1.25.1, podio version = 0.16.3
 - exact steps to reproduce the problem: checkout, setup environment (Geant, ROOT versions, iLCSoft release), cmake, build, run...
 - Input: open multiple edm4hep.root files either by ROOTFrameReader::openFiles() or ROOTFrameReader::openFile()
 - Output: crash at the beginning, but works fine with single file and reads the data
 - Goal: Read multiple edm4hep.root files

**Comment by tmadlener** [comment]
Thanks for reporting this. We will try to have a look as soon as possible, but it will potentially take until after next week since many of us will be at CHEP.

**Comment by wdconinc** [comment]
@lkosarz @c-dilks Can you add a more reproducible example, maybe connected with a fake PR that modifies `tests/read-multiple.cpp` to use `ROOTFrameReader`, if that reproduces the issue?

**Comment by tmadlener** [comment]
Thanks for providing a reproducer. We will have a look ASAP.

**Comment by lkosarz** [comment]
Thank you! My initial test was with openFiles() and passing of a pre-defined vector, so not on the fly. I did see the same crash happening in both openFiles() and multiple openFile() cases. I did also see memory leaks, but haven't checked it for this standalone code, I sent you. Maybe we should double-check for these too.
