### ISSUE TITLE
New podio Tag without c++20 prohibition

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/podio#419]
Now that ROOT 6.28/04 is out with c++20 support, it would be great if we could get a podio tag that doesn't forbid c++20 use. I.e., it includes #398 .

**Comment by tmadlener** [comment]
Actually scratch that, that is broken. Fixed in #420 (hopefully). Will make another tag once that is done and merged.

**Comment by andresailer** [comment]
Ok, thanks for the heads up!

**Comment by tmadlener** [comment]
Now we have one that should work with [v00-16-05](https://github.com/AIDASoft/podio/releases/tag/v00-16-05).
