### ISSUE TITLE
Mutability conversion fails on `push_back` to collection via Python bindings

### ISSUE THREAD

**Issue by bartosik-hep** [AIDASoft/podio#431]
Python bindings have been recently added to `edm4hep`, which don't work as expected in what regards the implicit conversion of mutable objects to immutable ones. In particular this happens in the following case:

```python
from edm4hep import edm4hep

collection = edm4hep.MCParticleCollection()
particle = edm4hep.MutableMCParticle()
particle.setPDG(22)
collection.push_back(particle)
```
producing the following error:
```c++
TypeError: void edm4hep::MCParticleCollection::push_back(edm4hep::MCParticle object) =>
    TypeError: could not convert argument 1
```

This error doesn't happen when an object is created directly in the collection:

```python
from edm4hep import edm4hep

collection = edm4hep.MCParticleCollection()
particle = collection.create()
particle.setPDG(22)
```

Setup description:
```
 - OS version: Alma Linux 9.2
 - Compiler version: GCC 11.3.1
 - PODIO version: 0.16.6
```

**Comment by tmadlener** [comment]
The actual issue is most likely in cppyy, but we should be able to work around this from our side, depending on how long it takes to fix this upstream
