### ISSUE TITLE
`PODIO_JSON_OUTPUT` not set downstream, but json support still compiled into libraries

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#435]
> *Note: this is a lazy copy from mattermost*

This seems to be caused as follows:
- during the build of EDM4hep, `PODIO_JSON_OUTPUT` is defined and libedm4hepDict.so includes the `to_json` function ([Component.h.jinja2](https://github.com/AIDASoft/podio/blob/master/python/templates/Component.h.jinja2#L43) is `inline`, but others aren't e.g. [Collection.cc.jinja2](https://github.com/AIDASoft/podio/blob/master/python/templates/Collection.cc.jinja2#L231)).
- during compiling with ROOT cling, the `#define` isn't set so it gets confused.

Here is a reproducer in our production environment which also works on my local spack with dd4hep, podio, edm4hep installed:
```console
ddsim --compactFile $DD4hepINSTALL/DDDetectors/compact/SiD.xml -G -N10 --outputFile SiD.edm4hep.root
root -l -q 'podio_issue.cxx+g("SiD.edm4hep.root")'
```
where `podio_issue.cxx` is
```c++
#include "ROOT/RDataFrame.hxx"
#include "TCanvas.h"

#include "edm4hep/MCParticleCollection.h"

int podio_issue(const char* fname)
{
  ROOT::RDataFrame df("events", fname);

  auto df0 = df.Define("n", "MCParticles.size()");
  auto h_n = df0.Histo1D({"h_n", "; N ", 10, 0, 10}, "n");

  auto c = new TCanvas();
  h_n->DrawCopy();
  return 0;
}
```

That returns
```console

Processing podio_issue.cxx+g("SiD.edm4hep.root")...
libedm4hepDict dictionary payload:267:7: error: no matching constructor for initialization of 'nlohmann::json' (aka 'basic_json<>')
  j = nlohmann::json{{"location", value.location},
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/nlohmann/json.hpp:892:5: note: candidate constructor not viable: requires at most 3 arguments, but 9 were provided
    basic_json(initializer_list_t init,
    ^
/opt/local/include/nlohmann/json.hpp:1007:5: note: candidate constructor not viable: requires 2 arguments, but 9 were provided
(etc)
```

**Comment by tmadlener** [comment]
I can also reproduce this in my development environment. Quickest workaround for now seems to be to add a `#define PODIO_JSON_OUTPUT` to each macro that wants to use this. Obviously that is not a longterm solution.

(Adding a few thoughts that we already partially discussed in private):
I gave putting all `to_json` function implementations into the respective headers a quick go, and that doesn't really work because then we would also have to start replacing forward declarations with `#include`s of the corresponding headers, which most likely is not viable because relations can lead to cyclic includes here.

I am also not sure whether we can make, e.g. a `#define EDM4HEP_PODIO_OUTPUT` that we *implicitly* generate based on the value of `PODIO_JSON_OUTPUT` work nicely. Maybe the cleanest solution would be to make this explicitly opt-in by creating a new option in the YAML file that enables / disables the json conversion.

**Comment by tmadlener** [comment]
Looking at the error message again, I think the problem is actually in an `inline` definition of a `to_json` function, as it is in `TrackState.h` which is a component. Not sure yet what that teaches us about the problem.

**Comment by tmadlener** [comment]
Maybe it would be easiest to remove the `#ifdef PODIO_JSON_OUTPUT` with a 
```cpp
#if __has_include("nlohmann/json.hpp")
  #include "nlohmann/json.hpp"
  // potentially a version check
  #define PODIO_JSON_OUTPUT // or something else for easier internal use
#endif
```
in that way we would at least not depend on some external `-DPODIO_JSON_OUTPUT`, but would have some (maybe) consistent internal check.

**Comment by wdconinc** [comment]
I think it seems like the Components just aren't guarded.

<details><summary>edm4hep/TrackState.h</summary>
<pre>
// AUTOMATICALLY GENERATED FILE - DO NOT EDIT

#ifndef EDM4HEP_TrackState_H
#define EDM4HEP_TrackState_H

#include "edm4hep/Vector3f.h"
#include <array>
#include <cstdint>
#include <ostream>

#ifdef PODIO_JSON_OUTPUT
#include "nlohmann/json.hpp"
#endif

namespace edm4hep {

class TrackState {
public:
  std::int32_t location{};              ///< for use with At{Other|IP|FirstHit|LastHit|Calorimeter|Vertex}|LastLocation
  float D0{};                           ///< transverse impact parameter
  float phi{};                          ///< azimuthal angle
  float omega{};                        ///< is the signed curvature of the track in [1/mm].
  float Z0{};                           ///< longitudinal impact parameter
  float tanLambda{};                    ///< lambda is the dip angle of the track in r-z
  float time{};                         ///< time of the track at this trackstate
  ::edm4hep::Vector3f referencePoint{}; ///< Reference point of the track parameters, e.g. the origin at the IP, or the
                                        ///< position  of the first/last hits or the entry point into the calorimeter.
                                        ///< [mm]
  std::array<float, 21> covMatrix{};    ///< lower triangular covariance matrix of the track parameters.  the order of
                                     ///< parameters is  d0, phi, omega, z0, tan(lambda), time. the array is a row-major
                                     ///< flattening of the matrix.

  static const int AtOther = 0; // any location other than the ones defined below
  static const int AtIP = 1;
  static const int AtFirstHit = 2;
  static const int AtLastHit = 3;
  static const int AtCalorimeter = 4;
  static const int AtVertex = 5;
  static const int LastLocation = AtVertex;
};

inline std::ostream& operator<<(std::ostream& o, const edm4hep::TrackState& value) {
  o << value.location << " ";
  o << value.D0 << " ";
  o << value.phi << " ";
  o << value.omega << " ";
  o << value.Z0 << " ";
  o << value.tanLambda << " ";
  o << value.time << " ";
  o << value.referencePoint << " ";
  for (int i = 0; i < 21; ++i) {
    o << value.covMatrix[i] << "|";
  }
  o << " ";

  return o;
}
</pre>
</details>
