### ISSUE TITLE
Trouble running `./install/tests/write``

### ISSUE THREAD

**Issue by shrey183** [AIDASoft/podio#44]
- OS version: Ubuntu 18.10
 - Compiler version: GCC 8.2.0
 - PODIO version: V00-09
 - Reproduced by: 

After preparing the environment and compiling with `init.sh`, I am trying to follow the instruction under the section titled **Running** on the README page. 

So I am in the directory: ~/podio/build and I try the following:

`../install/tests/write` 

this prints out information about particle 0 through particle 9 on the console.

Next, I ran 

`../install/tests/read`

which gives the following error: `bash: ../install/tests/read: No such file or directory`

It seems to me that the file example.root is not created. To verify installation, I ran 

`make test` from the build directory and apparently I am passing all the tests, but I can't understand why I am getting the above mentioned error.

**Comment by gaede** [comment]
It seems that some test program and file names have been changed in #40 without updating the
documentation and example scripts. From what I see `read` is now called `read-one` and `example.root` is now called `example1.root`.
I will look into providing a fix - but you should be able to continue for now.
