### ISSUE TITLE
PODIO_JSON_OUTPUT causes nlohmann/json.hpp in each include file, could be json_fwd.hpp instead

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#475]
- OS version: ubuntu 23.04
 - Compiler version: GCC 12.3
 - PODIO version: 0.16.5
 - Reproduced by: compiling github.com/eic/EICrecon ;-) (sorry)

When we compile EDM4hep with json support, the installed CMake config includes the line:
```cmake
set_target_properties(EDM4HEP::edm4hep PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PODIO_JSON_OUTPUT"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "podio::podio;nlohmann_json::nlohmann_json"
)
```
This causes `PODIO_JSON_OUTPUT` to be defined for all code that uses EDM4hep. This potentially affects a lot of files.

In the case of EICrecon, this results in the following build analysis (`clang -ftime-trace` with https://github.com/aras-p/ClangBuildAnalyzer):
```
**** Templates that took longest to instantiate:
134874 ms: nlohmann::basic_json<>::parse<const char *> (163 times, avg 827 ms)
 93952 ms: nlohmann::basic_json<>::basic_json (815 times, avg 115 ms)
 85261 ms: nlohmann::detail::parser<nlohmann::basic_json<>, nlohmann::detail::i... (163 times, avg 523 ms)
 71201 ms: nlohmann::detail::parser<nlohmann::basic_json<>, nlohmann::detail::i... (163 times, avg 436 ms)
 53404 ms: nlohmann::basic_json<>::json_value::json_value (817 times, avg 65 ms)
```
I.e. we spend almost 500s on just instantiating the json template in `json.hpp` out of the total compilation run. And we don't use json anywhere in this code :-\

It would be useful if downstream code could make the decision whether or not to enable this json support, or to use the `json_fwd.hpp` forwarding header, e.g. https://github.com/nlohmann/json#integration (this potentially requires some specific features of the nlohmann-json install, to ensure this header is available).

Happy to move this to EDM4hep too. Not sure where this is best addressed, but since the include lines live in the jinja templates here, I figured this would be the best place to start the discussion.

**Comment by tmadlener** [comment]
We could give the `json_fwd.hpp` a try to see if this solves things already. If that doesn't work I am not entirely sure yet how we could fix this.
