### ISSUE TITLE
Support for collection-level metadata

### ISSUE THREAD

**Issue by vvolkl** [AIDASoft/podio#49]
As discussed in the context of EDM4HEP support for some metadata, or any information that is saved together with a collection would be useful. For example, this could be used to save a readout string (`system:4,layer:5,module:18,x:-15,z:-15`) along with a dd4hep cellID. My first idea was to simply add a member to the collection template. @gaede , maybe you can comment how this is done in LCIO? Cheers

**Comment by andresailer** [comment]
LCIO collections have a LCParameters member to hold arbitrary collection parameters
http://lcio.desy.de/v02-09/doc/doxygen_api/html/classEVENT_1_1LCCollection.html#ac60df52bb014939521d2cc72ffe60223

http://lcio.desy.de/v02-09/doc/doxygen_api/html/classEVENT_1_1LCParameters.html

**Comment by andresailer** [comment]
Having a look at HepMC3: there are Attributes that can be attached to GenEvent (or other types)
http://hepmc.web.cern.ch/hepmc/group__attributes.html
