### ISSUE TITLE
Negative comparisons between `podio::ObjectID` objects are not implemented

### ISSUE THREAD

**Issue by jmcarcell** [AIDASoft/podio#495]
https://github.com/AIDASoft/podio/pull/493 breaks cases where there is a negative comparison between `podio::ObjectID()`, that is `id1 != id2`, because `podio::ObjectID` doesn't implement the negative comparison operator.

I think it's fine the few cases we have and we don't need to implement the operator, but also implementing it is a one liner.

**Comment by tmadlener** [comment]
Just out of curiosity. Did this break somewhere in the Key4hep stack? I thought I checked that by building a local version, but maybeI was missing some tests?

**Comment by jmcarcell** [comment]
Yes in CEPCSW, we also build it for the nightlies
