### ISSUE TITLE
podio-vis not installed by make install

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#501]
- OS version: ubuntu 23.04
 - Compiler version: gcc 12.3.0
 - PODIO version: master
 - Reproduced by: cmake -Bbuild -S. && make -Cbuild install
 - Goal: While `podio-dump` from `tools/` is installed by the CMakeLists.txt in that directory, `podio-vis` is not installed. This makes it impossible to use `podio-vis` unless you keep the source tree around and use it from there.

**Comment by tmadlener** [comment]
Good catch, (and also it looks like it is actually used). Do you want to add it here?

https://github.com/AIDASoft/podio/blob/4d6c0b7788ad13b9b5dcf5a92b627148c8b159f6/tools/CMakeLists.txt#L1

Otherwise, I will try to pick this up next week (remind me in case I forget).

**Comment by wdconinc** [comment]
Yeah I'll add it and put in a pr.

**Comment by wdconinc** [comment]
Yeah I'll add it and put in a pr.
