### ISSUE TITLE
EDM generation broken after install

### ISSUE THREAD

**Issue by gaede** [AIDASoft/podio#58]
As a result of #54 the EDM egenration does not work anymore for external  clients (EDM4Hep).
The reason is the hardcoded template_dir path "../templates" that is no longer available in the install.  @drbenmorgan  can you have a look at this ?

Current workaround:  
```
cd INSTALL_DIR
ln -s SOURCE_DIR/templates .
```

**Comment by drbenmorgan** [comment]
Hi @gaede, apologies for that, I'll get a fix Pull Request prepared.

**Comment by drbenmorgan** [comment]
Having had a quick look at this, there are a several ways to resolve this so thought better to discuss here before fixing in a Pull Request:

1. Restore original behaviour, so the install tree would look like:
   ```
   +- CMAKE_INSTALL_PREFIX/
      +- python/
      +- templates/
   ```
   The simplest, but will cause problems for packagers - e.g. say the install prefix is `/usr/local`, then `/usr/local/templates` is non-standard and could easily clash (I'm ignoring the `python dir` for now!).

2. Move `templates` as a subdirectory of `python`, so the relative path becomes "./templates". This is probably the best solution if the template files aren't for general access/use, i.e. only podio's python code will read them.

3. Update the relative path on install using known install locations to construct a relative path.

I'll implement whatever solution is preferred for podio. My personal recommendation would be the second one if the template files are only intended for internal use by podio's class generation.

**Comment by gaede** [comment]
Hi @drbenmorgan, I'd also vote for option 2). Can't think of any other use cases for the templates than from our python generators.

**Comment by gaede** [comment]
PS: shouldn't the `INSTALL_DIR/python` have a `podio` subdirectory in case someone wants to install to `/usr/local/` ?

**Comment by drbenmorgan** [comment]
Thanks @gaede, I'll go ahead and implement 2). 

You're right on the `INSTALL_DIR/python` issue, but `python/podio` also seems odd. Looking at the files in `python/`, there are some programs *and* modules

- programs: `podio_class_generator.py`, `podio_create_package.py`
- modules: `podio_config_reader.py`, `podio_templates.py`, `EventStore.py`

The former should probably go under a `bin/` subdirectory, but am not sure about the latter. I'd guess `lib/pythonX.Y/site-packages/podio`. Maybe just install them all to `bin` for now?

**Comment by drbenmorgan** [comment]
Ah scratch that install to `bin`, since that would stick `templates` under that which wouldn't be good.

**Comment by gaede** [comment]
How about having sth like:
```
/usr/local/include
/usr/local/lib
/usr/local/podio
/usr/local/podio/python
/usr/local/podio/templates
/usr/local/podio/...
```
Then we could easily add whatever is needed to ` /usr/local/podio/`  ?

**Comment by drbenmorgan** [comment]
I've submitted a Pull Request to fix the main issue using the 2nd option. Long term, it's probably best to think about a structure like:

```
+- bin/
    +- podio_class_generator
+- include/
    +- podio/
+- lib/
    +- libpodio.so
    +- ...dict...
    +- cmake/
    +- pythonX.Y/
       +- site-packages/
          +- podio/
             +- EventStore.py ?
             +- podio_config_reader.py ?
                 ...
```

That would require a little more work though, so thought best to submit the PR to get the fix in directly for now!

**Comment by peremato** [comment]
+1


On 27 Sep 2019, at 15:16, Ben Morgan <notifications@github.com<mailto:notifications@github.com>> wrote:


I've submitted a Pull Request to fix the main issue using the 2nd option. Long term, it's probably best to think about a structure like:

+- bin/
    +- podio_class_generator
+- include/
    +- podio/
+- lib/
    +- libpodio.so
    +- ...dict...
    +- cmake/
    +- pythonX.Y/
       +- site-packages/
          +- podio/
             +- EventStore.py ?
             +- podio_config_reader.py ?
                 ...


That would require a little more work though, so thought best to submit the PR to get the fix in directly for now!
