### ISSUE TITLE
Document the cmake functionality

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#604]
The cmake functionality that podio provides is not yet documented. There are several sets of slides where we have talked about it, but it hasn't found its way back into a markdown doument yet.

**Comment by hegner** [comment]
Do we want to use edm4hep as a non-trivial x-reference example in there? Or we stay self-contained?

**Comment by tmadlener** [comment]
In the slides I have used effectively edm4hep as example (with some minor tweaks to make it fit onto the slides), and I think it would make sense to cross reference at least the basics.

**Comment by tmadlener** [comment]
We have actually put this into proceedings as well at one point: https://inspirehep.net/literature/1911834
