### ISSUE TITLE
Add possibility to use range based for loops on relations and vector members

### ISSUE THREAD

**Issue by gaede** [AIDASoft/podio#61]
Add a helper class `vector_view` and code generation such that on can write range based for loops, e.g.
```
auto mcps = store.get<MCParticleCollection>("MCParticles") ;
for( auto& p : mcps ){
    for( auto& d : p.getDaughters() ) {
        printDaughter(d) ;
    }
}

```

**Comment by tmadlener** [comment]
This can be closed, as it was addressed by #107 (Wasn't closed automatically, because at the time of merging, the issue was not yet linked to the PR).
