### ISSUE TITLE
podio build on MacOS broken

### ISSUE THREAD

**Issue by gaede** [AIDASoft/podio#78]
I cannot build the latest podio on my macbook (see error message below).
I suspect it is due to the split of the root dependencies into a separate library in #69.
The dictionary depends on the `PythonEventStore` that in turn depends on the `ROOTReader` but the libpodioRootIO is not linked.
Naively making the following change:
```
target_link_libraries(podioDict PUBLIC podioRootIO ) #podio::podio ROOT::Core ROOT::Tree)
```
results in a cyclic dependency:
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "podioDict" of type SHARED_LIBRARY
    depends on "podioRootIO" (weak)
  "podioRootIO" of type SHARED_LIBRARY
    depends on "podioDict" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

@Andre: Any idea how to fix this  (and why it works on linux) ?

```
[  6%] Linking CXX shared library libpodioDict.so
cd /Users/gaede/podio/podio/build/src && /usr/local/Cellar/cmake/3.15.1/bin/cmake -E cmake_link_script CMakeFiles/podioDict.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++  -std=c++14 -stdlib=libc++ -O2 -g -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names  -o libpodioDict.so -install_name @rpath/libpodioDict.so CMakeFiles/podioDict.dir/podioDict.cxx.o -Wl,-rpath,/Users/gaede/podio/podio/build/src -Wl,-rpath,/data/ilcsoft/root/6.18.04/lib libpodio.so /data/ilcsoft/root/6.18.04/lib/libTree.so /data/ilcsoft/root/6.18.04/lib/libImt.so /data/ilcsoft/root/6.18.04/lib/libNet.so /data/ilcsoft/root/6.18.04/lib/libRIO.so /data/ilcsoft/root/6.18.04/lib/libThread.so /data/ilcsoft/root/6.18.04/lib/libCore.so 
Undefined symbols for architecture x86_64:
  "podio::ROOTReader::~ROOTReader()", referenced from:
      ROOT::delete_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
      ROOT::deleteArray_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
      ROOT::destruct_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by andresailer** [comment]
It works on linux because `-Wl,-no-undefined` isn't enabled.

If the event reader have to be part of the dictionary the undefined function implementations can be moved to the header file for example. 

Or maybe creating a second dictionary for the readers that is then part of podioRootIO

**Comment by gaede** [comment]
Thank, Andre,
I guess enabling `-Wl,-no-undefined` is not really an option, as it would then crash at run time,
wouldn't it ?
In #79 I have moved all virtual functions to ROOTReader.h, which works but is a but ugly.
Maybe in the long run we should consider re-organizing the libraries properly.
Also, I had to add ROOT includes and library to TestDataModel.

**Comment by andresailer** [comment]
No, the flag is just for the linker, but on clang with a different linker it is a different flag

**Comment by petricm** [comment]
Try
```cmake
  if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "AppleClang")
    SET ( CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,-undefined,error")
  elseif ( ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang") OR ( "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" ))
    SET ( CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--no-undefined")
  else()
    MESSAGE( WARNING "We do not test with the ${CMAKE_CXX_COMPILER_ID} compiler, use at your own discretion" )
  endif()
```

**Comment by gaede** [comment]
This is happily ignored by the linker:
```
cd /Users/gaede/podio/podio/build/src && /usr/local/Cellar/cmake/3.15.1/bin/cmake -E cmake_link_script CMakeFiles/podioDict.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++  -std=c++14 -stdlib=libc++ -O2 -g -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names  -Wl,-undefined,error -o libpodioDict.so -install_name @rpath/libpodioDict.so CMakeFiles/podioDict.dir/podioDict.cxx.o -Wl,-rpath,/Users/gaede/podio/podio/build/src -Wl,-rpath,/data/ilcsoft/root/6.18.04/lib libpodio.so /data/ilcsoft/root/6.18.04/lib/libTree.so /data/ilcsoft/root/6.18.04/lib/libImt.so /data/ilcsoft/root/6.18.04/lib/libNet.so /data/ilcsoft/root/6.18.04/lib/libRIO.so /data/ilcsoft/root/6.18.04/lib/libThread.so /data/ilcsoft/root/6.18.04/lib/libCore.so 
Undefined symbols for architecture x86_64:
  "podio::ROOTReader::~ROOTReader()", referenced from:
      ROOT::delete_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
      ROOT::deleteArray_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
      ROOT::destruct_podiocLcLPythonEventStore(void*) in podioDict.cxx.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by petricm** [comment]
Did you add the code sniped I posted?

**Comment by gaede** [comment]
Yes - as you can see in my post: ` -Wl,-undefined,error` is there ...

**Comment by andresailer** [comment]
That flag enables the error (or rather makes it explicit since error is the default value for the llvm/clang/macos linker), so with the current podio master this would be the expected output. To disable the error use `-Wl,-undefined,warning` (https://stackoverflow.com/a/26989988)

**Comment by andresailer** [comment]
Miss-clicked

**Comment by gaede** [comment]
This did not work either - finally `-Wl,-undefined,dynamic_lookup` did the trick, see #81.
With warning I got:
```
ld: can't use -undefined warning or suppress with -twolevel_namespace
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Anyways, I think that dynamic_lookup is what we really want and what we use on linux.

**Comment by petricm** [comment]
I think we had a long discussion once in DD4hep and agreed that `no-undefined` is what we really want :)

**Comment by gaede** [comment]
I remember that we had this discussion for DD4hep and that we had concluded that we want `no-undefined` but this does not work with podio (and the split of libraries) - see #81.
My understanding is that `-Wl,-undefined,dynamic_lookup ` causes the same behavior as the default on linux: allow the symbol to not be there when linking the library. It then later needs to be available at run time from some other library...

**Comment by gaede** [comment]
... and this is the case with our current tests - in particular the python reading....
