### ISSUE TITLE
Discussion on Schema Evolution 

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/podio#86]

**Comment by andresailer** [comment]
For example the change of meaning of the trackstate covariance
https://github.com/key4hep/EDM4hep/issues/107

**Comment by andresailer** [comment]
See slides and minutes: https://indico.cern.ch/event/1030566/

**Comment by andresailer** [comment]
One possible show case: https://github.com/key4hep/EDM4hep/issues/112
going from `unsigned long long` to `uint64_t`

**Comment by andresailer** [comment]
See slides https://indico.cern.ch/event/1134767/#6-schema-evolution-discussion

**Comment by tmadlener** [comment]
Partially tackled in #341

**Comment by tmadlener** [comment]
Closing this as the basics of schema evolution are in place and new issues probably are more specific.
