### ISSUE TITLE
libpodioDict.so is not always properly linked

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#90]
When building podio `libpodioDict.so` is not always properly linked into executables or other shared libraries, like `libpodioRootIO.so` or the test executables. I am not sure whether it is a podio problem or something that is more closely related to some subtle cmake issue, as it e.g. occurs on Ubuntu 18.04, but not on Fedora 29 (or on lxplus).

I have prepared an [Ubuntu docker image](https://hub.docker.com/repository/docker/tmadlener/ubuntu-podio-build-problem) where the problem occurs and a [Fedora docker image](https://hub.docker.com/repository/docker/tmadlener/fedora-podio-build-problem), where it does not.

To reproduce the problem in the Ubuntu container pull it and run it interactively, then do
```bash
bash build_podio.sh
```

This will build podio and run `tests/write > /dev/null` as well as `ldd tests/write` in the podio build directory. And result in output along the following lines

```
[...]
Error in <TTree::Branch>: The class requested (vector<podio::ObjectID>) for the branch "WithNamespaceRelationCopy#1" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (vector<podio::ObjectID>) to avoid to write corrupted data.
Error in <TTree::Branch>: The pointer specified for CollectionIDs is not of a class or type known to ROOT
	

        linux-vdso.so.1 (0x00007ffdfc9e1000)
	libTestDataModel.so => /home/hsf/podio/build/tests/libTestDataModel.so (0x00007f0b7867d000)
	libpodioRootIO.so => /home/hsf/podio/build/src/libpodioRootIO.so (0x00007f0b78472000)
	libpodio.so => /home/hsf/podio/build/src/libpodio.so (0x00007f0b78269000)
	libCore.so.6.20 => /home/hsf/root/lib/libCore.so.6.20 (0x00007f0b77b69000)
[...]
```

Repeating the same steps in the Fedora container leads to the following output, where only `ldd tests/write` is now present, since `tests/write > /dev/null` runs without problems.
```
[...]

        linux-vdso.so.1 (0x00007ffe1b542000)
	libTestDataModel.so => /home/hsf/podio/build/tests/libTestDataModel.so (0x00007f925746c000)
	libpodioRootIO.so => /home/hsf/podio/build/src/libpodioRootIO.so (0x00007f925745f000)
	libpodioDict.so => /home/hsf/podio/build/src/libpodioDict.so (0x00007f9257454000)
	libpodio.so => /home/hsf/podio/build/src/libpodio.so (0x00007f9257449000)
	libTree.so.6.20 => /home/hsf/root/lib/libTree.so.6.20 (0x00007f92572b5000)
[...]
```

The most important difference is that now `libpodioDict.so` is present.

To me it is currently unclear from where this difference arises, but it seems to be unrelated to the exact `gcc` version that is used on Ubuntu and also on how `root` has been built.

The only hint towards a problem can be seen when using `cmake-3.10` ~on Ubuntu~, where the following warning appears at the `cmake` stage

```
You have called ADD_LIBRARY for library podioDict without any source files. This typically indicates a problem with your CMakeLists.txt file
```

This message does not appear with newer cmake versions (tested with 3.14 and 3.17). It is also inconsequential as the outcome remains unchanged.

**Comment by andresailer** [comment]
The difference between podioDict linked and not is probably the linker version and the existence or default for the "--as-needed" option. If there is no symbol from podioDict used in the RootIO the linker chooses not to link the library when "--as-needed" is enabled.
I tried with the ubuntu container, adding `-Wl,--no-as-needed` before the podioDict library and the library was linked.

**Comment by andresailer** [comment]
In both instances the linker has the "as-needed" option, so maybe in one case it can better figure out that podioDict is needed, or the compiler is doing some ... 
In #91 I add no-as-needed around podioDict when it is linked into podioRootIO, which solves the problem for ubuntu.

**Comment by tmadlener** [comment]
It is definitely strange in my opinion. Apart from the possible (small) differences in the paths to `root`, `gcc`, etc. the output of `make VERBOSE=1` is exactly the same in both containers. But I also couldn't really find anything about the default values of the linker flags, especially since they are passed to it through gcc.

But as already mentioned in #91 it seems to be solved by adding `--no-as-needed` around `podioDict`

**Comment by andresailer** [comment]
So it is maybe this: gcc on ubuntu is configured to ad "as-needed" for the linker
https://askubuntu.com/questions/1077276/why-do-gccs-linker-options-as-per-dumpspec-contain-as-needed

**Comment by tmadlener** [comment]
Yes, I think that is very likely to be what is causing our problem. I am wondering how other projects handle this, since we can't be the only ones that want to link a root dictionary into a library, right?
