### ISSUE TITLE
Review implicit usage of ROOT globals in TTree handling

### ISSUE THREAD

**Issue by hegner** [AIDASoft/podio#93]
There are quite a few calls to ROOT relying on global states like creating TTrees implicitly within the current gDirectory. Would it make sense to be more explicit in these calls?

**Comment by tmadlener** [comment]
I am adding the proposal of a general review of the internals of the `ROOTReader` here as well. Currently the handling of switching files in the events `TChain` is not handled properly everywhere, (see e.g. #132). it might be worthwhile to check whether it is possible to do only once per event and keep track of which "local" event is currently being read.

**Comment by tmadlener** [comment]
This is handled properly for Frame writing (introduced in #287). See, e.g.:
https://github.com/AIDASoft/podio/blob/e8ae38b65ea81dc81d2fc3aebcf6c1679436a2e5/src/ROOTFrameWriter.cc#L29-L30

Closing this since the `ROOTReader` will eventually be deprecated (before v1.0)
